# Generated by Django 4.2.4 on 2023-09-10 06:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=4096, verbose_name='متن')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='تایید مدیر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('view_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='نام')),
                ('total_see', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مجموع بازدیدها')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(choices=[(1, 'فناوری'), (2, 'فشن'), (3, 'ورزشی'), (4, 'خوراکی'), (5, 'اخبار')], verbose_name='نام')),
                ('description', models.CharField(max_length=1024, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='سر برگ')),
                ('txt', models.CharField(max_length=16384, verbose_name='متن')),
                ('is_private', models.BooleanField(default=False, verbose_name='خصوصی')),
                ('pic', models.ImageField(default='', upload_to='', verbose_name='')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='تایید مدیر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به روز شده')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.tag', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='امتیاز')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='BlogApp.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=4096, verbose_name='متن اعتراض')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='تایید مدیر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complained_comment', to='BlogApp.comment', verbose_name='دیدگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complaine', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='BlogApp.post', verbose_name='پست'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
